### ISSUE TITLE
Status?

### ISSUE THREAD

**Issue by maelle** [ropensci/RedisAPI#9]
@richfitz should this repo get a suspended/abandoned badge and be archived? In that case it'd be best to close all issues and to add a stop sign in the repo description cf https://github.com/ropensci?utf8=%E2%9C%93&q=&type=archived&language= (because GitHub archived repos don't look much different from normal repos). It wouldn't disappear, it'd be read-only.

**Comment by maelle** [comment]
Or of course add any more appropriate status badge, and sorry if I interpreted activity wrong and if it shouldn't be archived :-) http://www.repostatus.org/

**Comment by richfitz** [comment]
Fixed in d6f8a01
